namespace IntegradorApi.Data.Enums;

public enum Linguagens {
    AFRIKAANS, ALBANIAN, ARABIC, ARMENIAN, AZERBAIJANI, BASQUE, BELARUSIAN,
    BENGALI, BULGARIAN, CATALAN, CHINESE, CROATIAN, CZECH, DANISH, DUTCH,
    ENGLISH, ESTONIAN, FILIPINO, FINNISH, FRENCH, GALICIAN, GEORGIAN,
    GERMAN, GREEK, GUJARATI, HAITIAN_CREOLE, HEBREW, HINDI, HUNGARIAN,
    ICELANDIC, INDONESIAN, IRISH, ITALIAN, JAPANESE, KANNADA, KOREAN,
    LATIN, LATVIAN, LITHUANIAN, MACEDONIAN, MALAY, MALTESE, NORWEGIAN,
    PERSIAN, POLISH, PORTUGUESE, PORTUGUESE_GOOGLE, ROMANIAN, RUSSIAN,
    SERBIAN, SLOVAK, SLOVENIAN, SPANISH, SWAHILI, SWEDISH, TAMIL, TELUGU,
    THAI, TURKISH, UKRAINIAN, URDU, VIETNAMESE, WELSH, YIDDISH,
    CHINESE_SIMPLIFIED, CHINESE_TRADITIONAL
}